---

- name: Setup {{service_item}}
  include: includes/setup.yml

- name: Make uploads directory.
  file:
    path: "{{ volumes_root }}/bookstack/uploads"
    state: directory
    # This sets the directory to www-data/www-data ownership inside the container
    owner: '33'
    group: '33'
    mode: '0755'

- name: Make storage uploads directory.
  file:
    path: "{{ volumes_root }}/bookstack/storage-uploads"
    state: directory
    # This sets the directory to www-data/www-data ownership inside the container
    owner: '33'
    group: '33'
    mode: '0755'

- name: Start {{service_item}}
  include: includes/start.yml
